### ISSUE TITLE
Update limit monitoring with checks for lowering repeat notifications

### ISSUE THREAD

**Issue by jordanpadams** [NASA-AMMOS/AIT-GUI#92]
RIght now, if a limit trip continues for an extended period of time, you get bombarded with email notifications. This feature will allow for the ability to receive only every 30th (?) notification.

**Comment by aywaldron** [comment]
After talking with @MJJoyce I'm thinking of adding the following config options to `config.notifications`. 
- Option for number of times limit exceeded before notification triggered. This would be for cases where limits are known to be exceeded briefly before returning to normal, so a notification is not required if it is in the error range only briefly. 
- Option for frequency of notifications (in terms of time or number of consecutive errors). Would reset each time value exceeds limits again. 

Both of these would require keeping track of how long (time and number of packets) a value has been out of limits, and what range the last packet was in. 

```
    notifications:
        email:
            triggers:
                - limit-warn
                - limit-error
            recipients:
                - email@address.com
        options:
            frequency:
                packets: 30  # every 30 packets
                seconds: 120  # every 2 minutes
                # if both are specified, use whichever is most frequent
                # would like suggestions on what the defaults should be
            threshold: 
                 packets: 5  # notifies only if out of range for 5+ consecutive packets
                 seconds: 60  # notifies only if out of range for 60+ seconds
                 # if both specified, use whichever happens first
                 # default both to 0
```
